### ISSUE TITLE
Doku: Fehlende Ergänzungen und Korrekturen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1036]
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/147
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/139
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/137
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/113
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/71
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/59
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/46
- [x] ~https://github.com/yakamara/redaxo_yform_docs/issues/43~
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/38
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/27
- [x] https://github.com/yakamara/redaxo_yform_docs/issues/26
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/23
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/16
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/13
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/10
- [ ] https://github.com/yakamara/redaxo_yform_docs/issues/3
- [x] https://github.com/yakamara/redaxo_yform/issues/1081

**Wer sich beteiligen möchte, bitte einen PR machen und hierauf verweisen - bitte hier nicht kommentieren.**

**Comment by dergel** [comment]
Ich glaube leider nicht daran, dass sich jemand so an diese Liste macht, aber gerne übernehme ich sie immer in den nächsten Milestone und vielleicht komme ich ja selber dazu.

**Comment by alxndr-w** [comment]
@dergel das verstehe ich. Ich glaube auch generell nicht mehr daran, dass das jemand macht, wenn nicht ich oder du. 

Am liebsten gemeinsam, manche Sachen habe ich bis heute selbst nicht verstanden und wir können gerne mal eine Stunde Zeit finden, das meiste abzuhaken.

**Comment by alxndr-w** [comment]
Wenn, dann würde ich nochmal grundsätzlich an der Doku arbeiten. Vieles davon findet auch "drübern" bei den FOR Tricks statt, was eigentlich hier dazu gehört. Es fühlt sich an wie ein Fass ohne Boden. Auch rund 3 Jahre später habe ich bestimmte Dinge in YForm nicht verstanden, insofern kann ich sie ohne Ratgeber nicht erklären oder dokumentieren.
