### ISSUE TITLE
4.0.0 CSV-Import: $id has to be an integer greater than 0, but "" given

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1209]
Zum Reproduzieren

* Tabelle mit Datensätzen über den Table Manager als CSV exportieren
* Bestehende Datensätze ergänzen
* CSV importieren

Verhalten: Import wird abgebrochen.
Erwartetes Verhalten: neue Datensätze ohne id sollten automatisch als INSERT eine ID vergeben bekommen.

**Comment by dergel** [comment]
Hat bei meinem Test gerade geklappt. War die einfachsten Form. id und name und dann im Export eine neue id und neuen Namen ergänzt und ging. Ich schliesse das mal. Wenn es klarer wird was es genauer ist, gerne reopen

**Comment by alxndr-w** [comment]
Hast du id leer gelassen?

**Comment by dergel** [comment]
Stimmt.. ich glaube, das habe ich nicht. Nur neue ergänzt. Nehme ich auf und prüfe es

**Comment by alxndr-w** [comment]
scheinbar gefixt in #1364
