### ISSUE TITLE
YOrm: Rückgabe-Klasse von `getRelatedDataset()` und `getRelatedCollection()` definieren können.

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1251]
Ich habe ein Addon, welches `rex_yform_manager_dataset` erweitert

```
<?php
class event_category extends \rex_yform_manager_dataset
{
}
```

```
<?php
class event_date extends \rex_yform_manager_dataset
{
    public function getCategories()
    {
        $this->categories = $this->getRelatedCollection('event_category_id');
        return $this->categories;
    }
}
```

und darauf aufbauend ein weiteres Addon
```
<?php

class msg_event_category extends event_category
{
// Eigene Methoden
}
```
``` 
<?php

class msg_event_date extends event_date
{
    public function getCategories()
    {
        $this->categories = $this->getRelatedCollection('event_category_id');
        return $this->categories;
    }
}
```
Wenn ich im Objekt von `msg_event_date`  die Methode `getRelatedCollection()` aufrufe, erhalte ich ein `event_category`-Objekt zurück und kein `msg_event_category`-Objekt. 

Wie kann ich definieren, nach welcher dataset-Klasse sich `getRelatedCollection()` oder `getRelatedDataset()` richten soll?

**Comment by dergel** [comment]
Das lehnt sich hier an .. https://github.com/yakamara/redaxo_yform/issues/1252 
Im Moment ist das nicht vorgesehen. Ich schaue mir das aber noch mal an. Vielleicht gibt ja andere Wege.

**Comment by alxndr-w** [comment]
In https://github.com/yakamara/ycom/pull/477 habe ich mir einen alternativen Ansatz überlegt - nämlich selbst festlegen zu können, ob  überhaupt das Addon die Model Class definiert - oder ob ich ggf. eine eigene Klasse definieren kann, die auf der Standard-Klasse aufbaut.

**Comment by DanielWeitenauer** [comment]
@alxndr-w Das scheint mir eher ein YForm-Problem zu sein. Es wird ja immer die Klasse benutzt, die du gerade per `setModelClass `auf die Tabelle gemappt hast. Evtl. gibt es die Mögilichkeit, die `getRelated..` Methoden in deinen Klassen so zu überschreiben und anzupassen, dass du vor dem Aufruf dein Mapping setzt und danach das ursprüngliche wieder zurückschreibst.

**Comment by alxndr-w** [comment]
Auf die Idee bin ich nicht gekommen, ich probiere das Mal aus. @DanielWeitenauer danke!

**Comment by alxndr-w** [comment]
Mir war gar nicht klar, dass man das zur Laufzeit ändern kann. Das löst mein Anliegen.

```php

$original = rex_yform_manager_dataset::getModelClass('rex_event_date');

rex_yform_manager_dataset::setModelClass(
    'rex_event_date',
    custom_event_date::class
);

$category = event_category::get(1);
$dates = $category->getRelatedCollection('date_id');

rex_yform_manager_dataset::setModelClass(    
    'rex_event_date',
    event_date::class
);
```
