### ISSUE TITLE
validate im Table Manager - mehrere Felder sollten Leerzeichen oder Umbruchzeichen erhalten

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1338]
Es muss eins von 32 Feldern ausgefüllt werden. Die Felddefinition sieht daraufhin so aus:

![image](https://user-images.githubusercontent.com/3855487/209832863-427ae80c-5c3e-4e1d-a591-2449ca8c0bd0.png)

Es fehlt eine Umbruchmöglichkeit.

**Comment by dergel** [comment]
es geht um die Darstellung, oder?

**Comment by alxndr-w** [comment]
Ja. Es fehlt ein Leerzeichen oder etwas, das einen Zeilenumbruch erlaubt.
