### ISSUE TITLE
im Table Manager des YForm funktioniert die Massenbearbeitung von Datensätzen nicht mehr

### ISSUE THREAD

**Issue by marcohanke** [yakamara/yform#1418]
Ungetestet aus Slack:
Eingestellt unter YForm / Table Manager / (in Tabellenübersicht) Tabelle editieren / Benutzer-Komfortfunktionen / Massenbearbeitung erlauben. Unsere Anwendung der Funktion: Die Datensätze verfügen über ein Feld "Exportiert", um bereits (als CSV) exportierte Datensätze zu kennzeichnen: 1 (bereits exportiert), 0 (noch nicht exportiert). Ich suche nach "Exportiert" = 0, gehe auf "Datenergebnis editieren", aktiviere 'Feld "Exportiert" bearbeiten', setze das Häkchen bei "Exportiert" und speichere. Aufgefallen ist das der Kundin nach dem Update auf die aktuelle 4.1.1. Ich kann nicht sicher sagen, ob die Massenbearbeitung mit der Version 4.0.2 noch funktionierte oder ob das Problem schon länger besteht. - Nun habe ich die Datensätze als Service per Update-Skript angepasst, aber die Kundin schätzt die Funktion. Wäre schön, wenn die Reparatur auf die Update-Liste käme. Vielen Dank!

**Comment by alxndr-w** [comment]
Kann ich nicht bestätigen. Es gibt kein mir bekanntes Feature in YForm, welches exportierte Datensätze als exportiert markiert.

**Comment by dergel** [comment]
update funktioniert bei meinen Tests. Kannst du mir ein Tableset erstellen mit welchem das nicht klappt und ich prüfe das damit?

**Comment by marcohanke** [comment]
Öhm, ich kann mich nicht erinnern dass Issue geschrieben zu haben und hab' keine Ahnung in welchem Projekt das war 😬🙈
