### ISSUE TITLE
Löschen von mehrfach verschachtelten Inline-Relations ist fehlerhaft

### ISSUE THREAD

**Issue by xong** [yakamara/yform#1420]
Inlinerelation-Datensätze, die mehrfach verschachtelt sind, werden nicht korrekt gelöscht.

Beispiel "Veranstaltung":

- Raum A
  - Programmpunkt A.1
  - Programmpunkt A.2
- Raum B
  - Programmpunkt B.1

Die Räume sind Inlinerelations der Veranstaltung und Programmpunkte sind Inlinerelations der Räume.

Das Löschen von Programmpunkt B.1 über den "removeme"-Button entfernt Programmpunkt A.1.

Das Problem tritt nur bei gespeicherten Datensätzen auf, die aus der Datenbank geladen werden, d. h. fügt man einen Programmpunkt hinzu, ohne direkt zu speichern, und löscht ihn, dann funktioniert das.

Das Problem besteht mindestens seit Version 4.0.4.

**Comment by dergel** [comment]
das sollte mittlerweile passen. Ich konnte den Fehler nict mehr nachvollziehen.
