### ISSUE TITLE
Feldtyp datetime_local funktioniert nicht im Firefox

### ISSUE THREAD

**Issue by Koala** [yakamara/yform#1450]
Der Feldtyp `datetime_local` funtktioniert derzeit nicht vollständig im Firefox (getestet mit FF 118). Das Datum wird übernommen, es gibt aber keine Auswahlmöglichkeit für eine Uhrzeit.
Das Problem tritt dann auf, wenn zuvor über den Button "Leeren" im Datepicker Datum und Zeit "gelöscht" wurden. Danach kann nur ein Datum gewählt werden, es fehlt aber die Uhrzeit. Diese kann dann nur händisch jeweils für Stunde und Minute neu gesetzt werden.

![grafik](https://github.com/yakamara/redaxo_yform/assets/330686/3c2305d1-b1c2-4c53-8cc5-930f63de6e47)

Es gibt dazu auch einen Bugreport auf Bugzilla: [Make <input type=datetime-local> show a time picker too.](https://bugzilla.mozilla.org/show_bug.cgi?id=1726108) und hier ist auch etwas dazu beschrieben: [html.elements.input.input-datetime-local - Not fully supported in Firefox](https://github.com/mdn/browser-compat-data/issues/16138)

Bis es dafür eine Lösung gibt, wäre es möglich bei fehlender Zeitangabe einfach `00:00` einzutragen?
(also bei der Prüfung der Daten vor dem Speichern)

#datetime-local #datetime_local

**Comment by alxndr-w** [comment]
Der Feldtyp ist von https://github.com/alexplusde/yform_field, nicht von YForm. Issue hier bitte schließen.
