### ISSUE TITLE
Table Manager: `integer` und `number`-Feld: Default-Wert wird nicht übernommen.

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1458]
Stattdessen wird als Default-Wert `0` ausgegeben.

https://github.com/yakamara/yform/blob/master/lib/yform/value/integer.php
https://github.com/yakamara/yform/blob/master/lib/yform/value/number.php

**Comment by tyrant88** [comment]
Kann ich nicht bestätigen - funzen wie erwartet:
![Zwischenablage-1](https://github.com/user-attachments/assets/5bb6122d-4021-45ea-b033-99ffa3af59eb)

**Comment by alxndr-w** [comment]
Ich kann's ein Jahr später nur im Table Manager nachstellen, wenn eine ungültige Zahl eingegeben wurde (Komma statt Punkt, Text hinten dran) - dann bleibt es leer. (Was ich okay finde)

![image](https://github.com/user-attachments/assets/7a5f0cf1-ac11-4966-8bdc-0a713d3e4b5b)
![image](https://github.com/user-attachments/assets/7fd379d6-9a54-4621-b520-4d842e66ff31)
