### ISSUE TITLE
RESTful API: Auf Domain beschränken können, um Abruf via JS einzuschränken, die den Token preisgeben

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1468]
(Ähnlich wie bspw. bei Google APIs: Beschränkung auf IPs/IP-Räume und/oder clientseitige Domains)

**Comment by dergel** [comment]
das sehe ich nicht als Option im REST PlugIn, müsste man selbst vorher abfangen. z.B. indem man die IP abfragt und wenn ok, nur dann die REST API initialisiert.
