### ISSUE TITLE
Table Manger: E-Mail-Templates: Löschen schlägt fehl

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1478]
**rex_sql_exception:** Error while executing statement "delete from rex_yform_email_template where id=:template_id" using params {"tempplate_id":5}! SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 406

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                  | Line     |
| -------------------------------------------- | ----------------------------------------------------- | -------- |
| rex_sql->execute                             | redaxo/src/core/lib/sql/sql.php                       | 449      |
| rex_sql->setQuery                            | redaxo/src/addons/yform/plugins/email/pages/index.php | 42       |
| require                                      | redaxo/src/core/lib/packages/package.php              | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                 | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                    | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                 | 504      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                 | 453      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/yform/pages/index.php               | 3        |
| require                                      | redaxo/src/core/lib/packages/package.php              | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                 | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                    | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                 | 504      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                 | 436      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                           | 241      |
| require                                      | redaxo/src/core/boot.php                              | 155      |
| require                                      | redaxo/index.php                                      | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.1.27, MySQL 5.7.44)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.27     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MySQL 5.7.44                   |
| Character set | utf8mb4                        |
|       Warning | Die verwendete MySQL-Version 5.7.44 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/121.0.0.0 |
|      Protocol | HTTP/2.0         |
|         HTTPS | yes              |

| Packages                          |            |
| --------------------------------: | :--------- |
|                      accessdenied | 2.1.0      |
|                            across | 4.0.0-dev1 |
|                           adminer | 1.9.3      |
|                            backup | 2.9.0      |
|                       be_password | 2.0.1      |
|                          be_style | 3.2.0      |
|               be_style/customizer | 3.2.0      |
|                   be_style/redaxo | 3.2.0      |
|                   be_style_fluent | 4.0.1      |
|                          be_tools | 1.8.0      |
|                           bloecks | 3.1.1      |
|                  bloecks/cutncopy | 3.1.1      |
|                     cache_warm_up | 1.1.0-dev  |
|                      cache_warmup | 4.0.0      |
|                              cke5 | 6.1.0      |
|                   consent_manager | 4.2.0      |
|                           cronjob | 2.10.0     |
|                           cropper | 2.0.2      |
|                         developer | 3.9.2      |
|                             feeds | 4.0.7      |
|                        focuspoint | 4.0.4      |
|                   global_settings | 2.8.4      |
|                          icecoder | 3.0.2      |
|                           install | 2.11.1     |
|                      link_checker | 1.0.0-dev  |
|                       maintenance | 2.9.2      |
|                          markitup | 3.7.4      |
|            markitup/documentation | 1.1.0      |
|                            mblock | 3.4.13     |
|                     media_manager | 2.14.0     |
|          media_manager_responsive | 1.1.5      |
|                         mediapool | 2.13.0     |
|                          metainfo | 2.10.0     |
|                             mform | 7.3.0      |
|                        mform/docs | 1.1        |
|                            minify | 2.2.1      |
|                         phpmailer | 2.12.0     |
|                           project | dev        |
|                   project_manager | 1.5.1      |
|            project_manager/client | 1.1.0      |
|                             qanda | 2.2.0      |
|                  quick_navigation | 6.1.0      |
|                         redactor2 | 4.2.1      |
|                         search_it | 6.10.1     |
|           search_it/documentation | 6.10.1     |
|                          speed_up | 1.4.0      |
|                             sprog | 1.5.1      |
|                        statistics | 3.1.0      |
|                         structure | 2.15.0     |
|                 structure/content | 2.15.0     |
|                 structure/history | 2.15.0     |
|                  structure_tweaks | 1.4.1      |
|                             theme | 1.4.0      |
|                          ui_tools | 1.2.2      |
| ui_tools/bootstrap-datetimepicker | 4.17.47    |
|        ui_tools/jquery-minicolors | 2.4.0      |
|                ui_tools/selectize | 0.2.0      |
|                          uploader | 2.4.2      |
|                               url | 2.1.0      |
|                       usage_check | 3.0        |
|                             users | 2.10.0     |
|                            watson | 2.3.0      |
|                     xoutputfilter | 3.0.0      |
|              xoutputfilter/abbrev | 3.0.0      |
|             xoutputfilter/backend | 3.0.0      |
|       xoutputfilter/documentation | 1.0.0      |
|            xoutputfilter/frontend | 3.0.0      |
|       xoutputfilter/import_export | 3.0.0      |
|                              ycom | 4.2.1      |
|                         ycom/auth | 4.2.1      |
|                             yform | 4.1.1      |
|                       yform/email | 4.1.1      |
|                     yform/manager | 4.1.1      |
|                       yform/tools | 4.1.1      |
|             yform_spam_protection | 1.2.3      |
|                   yform_usability | 2.1.4      |
|                          yrewrite | 2.10.0     |
|                       zip_install | 1.4.0      |

</details>

**Comment by dergel** [comment]
kann ich nicht nachvollziehen und finde auch kein "tempplate_id" irgendwo im Code, also mit doppelt "p".

**Comment by alxndr-w** [comment]
Ja, das ist ja Mal schräg.

Mit einem Update auf 4.2.0 war's auch gelöst, dennoch seltsam.
