### ISSUE TITLE
customLink `ylink` funktioniert nicht mehr mit yform 4.2.0

### ISSUE THREAD

**Issue by ynamite** [yakamara/yform#1483]
**Description / Beschreibung**

Das Popup öffnet sich zwar, aber beim Versuch einen Datensatz auszuwählen, erscheint in der Konsole
```
Uncaught TypeError: Cannot set properties of null (setting 'value')
```

yform manager triggered den Event `rex:YForm_selectData` nicht mehr.

**Affected versions / Verwendete Versionen**
yform 4.2.0
mform 7.4.0

**Comment by ynamite** [comment]
https://github.com/FriendsOfREDAXO/mform/issues/306

**Comment by skerbis** [comment]
Fehlermeldung in der Konsole bei mir: 
TypeError: null is not an object (evaluating 'opener.document.getElementById('yform-dataset-view-'+opener_id).value = value')

**Comment by skerbis** [comment]
Achtung es hat auch Auswirkung auf CKE5, redactor, TinyMCE und Co.  ... ich finde es nicht gut, dass wir jetzt sämtliche AddOns anpassen müssen. Bitte lasst das Jquery erstmal drin. Das bekommen wir so schnell nicht gefixt. @dergel

**Comment by ynamite** [comment]
@skerbis @dergel man könnte auch mal beide Variante drin lassen.
Sollte keine Konflikte geben, wenn beide laufen. jQuery legt den Listener auf das neu erstellte Popup, mit Native JS muss der Listener aber auf `window`.

**Comment by dergel** [comment]
Für mich ok. Dann halt nur deprecated dran, damit uns das noch bewusst ist. Danke für die Hilfe
