### ISSUE TITLE
HTML in Table-Ansicht wird nicht geparsed

### ISSUE THREAD

**Issue by dpf-dd** [yakamara/yform#1490]
<img width="641" alt="Bildschirmfoto 2024-03-26 um 09 42 05" src="https://github.com/yakamara/yform/assets/10958385/cd609537-0661-432f-ba77-f3d67d9fcc60">

Redaxo 5.17.0
yForm 4.2.1

Kleiner Bug, zum Glück reine Kosmetik... :)

**Comment by tbaddade** [comment]
https://github.com/yakamara/yform/issues/1486
