### ISSUE TITLE
Cannot use "::class" on string

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#1535]
**TypeError:** Cannot use "::class" on string
**File:** src\addons\yform\plugins\manager\lib\yform\manager\search.php
**Line:** 135

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                   | Line     |
| -------------------------------------------- | ------------------------------------------------------ | -------- |
| rex_yform_manager_search->getQueryFilter     | src\addons\yform\plugins\manager\lib\yform\manager.php | 754      |
| rex_yform_manager->getDataListQuery          | src\addons\yform\plugins\manager\lib\yform\manager.php | 514      |
| rex_yform_manager->getDataPage               | src\addons\yform\plugins\manager\pages\data_edit.php   | 20       |
| include                                      | src\addons\neues\pages\yform.php                       | 76       |
| require                                      | src\core\lib\packages\package.php                      | 233      |
| rex_package->includeFile                     | src\core\lib\be\controller.php                         | 517      |
| rex_be_controller::{closure}                 | src\core\lib\util\timer.php                            | 62       |
| rex_timer::measure                           | src\core\lib\be\controller.php                         | 499      |
| rex_be_controller::includePath               | src\core\lib\be\controller.php                         | 465      |
| rex_be_controller::includeCurrentPageSubPath | src\addons\neues\pages\neues.php                       | 15       |
| require                                      | src\core\lib\packages\package.php                      | 233      |
| rex_package->includeFile                     | src\core\lib\be\controller.php                         | 517      |
| rex_be_controller::{closure}                 | src\core\lib\util\timer.php                            | 62       |
| rex_timer::measure                           | src\core\lib\be\controller.php                         | 499      |
| rex_be_controller::includePath               | src\core\lib\be\controller.php                         | 439      |
| rex_be_controller::includeCurrentPage        | src\core\backend.php                                   | 253      |
| require                                      | src\core\boot.php                                      | 157      |
| require                                      | public\redaxo\index.php                                | 12       |

</details>
<details>
<summary>System report (REDAXO 5.18.0, PHP 8.3.7, MariaDB 10.11.9)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.18.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.3.7      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.9 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.59  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/130.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | yes              |

| Packages                 |                      |
| -----------------------: | :------------------- |
|             2factor_auth | 2.3                  |
|             accessdenied | 3.0.0                |
|                  adminer | 2.0.2                |
|              auto_delete | 1.0.2                |
|                   backup | 2.9.1                |
|              be_password | 2.0.1                |
|                 be_style | 3.5.0                |
|      be_style/customizer | 3.5.0                |
|          be_style/redaxo | 3.5.0                |
|                  bloecks | 4.0.2                |
|         bloecks/cutncopy | 4.0.2                |
|                  cronjob | 2.11.0               |
|                developer | 3.9.2                |
|               iconpicker | 2.0.0                |
|                  install | 2.12.1               |
|           mailer_profile | 1.3.2                |
|              maintenance | 3.2.1                |
|                   mblock | 3.4.13               |
|            media_manager | 2.17.0               |
| media_manager_responsive | 2.0.0-dev-2024-09-14 |
|                mediapool | 2.15.0               |
|                 metainfo | 2.11.0               |
|                    mform | 8.0.4                |
|                    neues | 6.0.0-dev-2024-09-16 |
|                phpmailer | 2.14.0               |
|                 plus_bs5 | 0.1.5                |
|                  product | 3.0.0                |
|                  project | dev                  |
|          project_manager | 1.5.3                |
|   project_manager/client | 1.1.0                |
|                    qanda | 2.2.2                |
|         quick_navigation | 8.1.3                |
|                 redactor | 2.5.2                |
|                 respondo | 0.0.1-dev-2024-04-07 |
|                  rexstan | 1.0.192              |
|                schwooops | 0.0.1-dev-2024-08-26 |
|                search_it | 6.11.2               |
|  search_it/documentation | 6.10.1               |
|                 speed_up | 1.4.0                |
|                    sprog | 1.5.1                |
|                    staff | 1.4.1                |
|          stellenangebote | 3.0.0-beta2          |
|                structure | 2.17.2               |
|        structure/content | 2.17.2               |
|                    thumb | 1.0.0-dev-2024-09-09 |
|                 uploader | 2.4.2                |
|                      url | 2.1.0                |
|                    users | 2.11.0               |
|                warehouse | 2.0.0-dev            |
|          wenns_sein_muss | 5.1.0                |
|                 wildcard | 1.0.0                |
|                     ycom | 4.3.0                |
|                ycom/auth | 4.3.0                |
|               ycom/group | 4.3.0                |
|               ycom_board | 4.0.0-dev-2024-10-14 |
|                  ydeploy | 2.0.2                |
|                    yform | 4.2.1                |
|              yform/email | 4.2.1                |
|            yform/manager | 4.2.1                |
|               yform/rest | 4.2.1                |
|              yform_field | 2.7.2                |
|            yform_geo_osm | 1.2.9                |
|         yform_quick_edit | 1.0.1                |
|          yform_rapidmail | 1.0.3                |
|    yform_spam_protection | 1.2.6-dev            |
|          yform_usability | 2.1.4                |
|                     ymca | 2.2.0                |
|                 yrewrite | 2.10.0               |
|        yrewrite_metainfo | 2.1.1                |

</details>

**Comment by DanielWeitenauer** [comment]
Es könnte ein Problem mit einem der eingesetzten (Custom-)Feldern geben. Als Rückgabewert der Methode `getSearchFilter` wird ein Objekt erwartet (z.B. `rex_yform_manager_query`). Es wird aber wohl nur ein String zurückgegeben. 
Typehints oder eine zusätzliche Prüfung, ob tatsächlich ein Objekt zurückkommt, könnten das Problem präzisier eingrenzen.
Dennoch ist es wahrscheinlich sinnvoll, auch die Rückgabewerte der Methode `getSearchFilter` in den eingesetzten Feldern zu prüfen.

**Comment by alxndr-w** [comment]
Danke für den Hinweis. Das scheint in der aktuellen Installer-Version auch noch uneinheitlich zu sein, zukünftig jedoch wohl nicht mehr.

Hier wurden früher wohl auch string-Werte per return zurückgegeben, das ist wohl hinfällig.

Die Domain-Auswahl in yform_field und an anderer Stelle werde ich hoffentlich neu auf Choice aufbauen können.
