### ISSUE TITLE
Performance verbessern

### ISSUE THREAD

**Issue by staabm** [yakamara/yform#295]
Zitat aus slack (von gregor)

> Gerade mal lokal geschaut. einen deutlichen Anstieg bei der Skripttime unten im Footer kann ich bei mir auch mit yform sehen (mehrere tabellen).
allerdings ist es trotzdem noch nicht langsam.
beispiel benutzer-page: ohne yform ca 80ms, mit yform ca. 180ms

D.h. Yform alleine kostet mehr resourcen als der ganz rex core

Müsste man mal profilen

**Comment by alexplusde** [comment]
@staabm würdest du das Thema hier nochmal angehen wollen? Vielleicht mit einem Muster-Projekt? Zumindest auszugsweise, denn YForm ist ja schon sehr mächtig und wird unterschiedlich benutzt.

**Comment by staabm** [comment]
wenn mir jemand ein muster projekt zur verfügung stellen kann, gerne.

ich selbst hab noch nie mit dem addon gearbeitet und hab keine vergleichswerte

**Comment by dergel** [comment]
Meines Erachtens ist das bereits behoben. Sollte es wieder langsame Varianten geben, bitte neues Issues mit Testset
