### ISSUE TITLE
upload-Feld: multiple-Attribut zulassen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#430]
Und ggf. alle daraus resultierenden Folgen (mehrere Dateien auf einmal) beachten.

https://caniuse.com/#feat=input-file-multiple

**Comment by alxndr-w** [comment]
@dergel das hatte ich für die 4.0 ebenfalls auf dem Schirm.

**Comment by dergel** [comment]
4.0 wird es nicht mehr - aber ich schiebe es "mal" auf 4.1 - ohne Garantie. Das ist ein großes Issue
