### ISSUE TITLE
manager: Choice-Feld: Einträge ohne Gruppe nicht einrücken, Favoriten optional nicht einrücken

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#524]
ist:
![image](https://user-images.githubusercontent.com/3855487/46024610-7a803100-c0e7-11e8-9fd9-1aa009ab6e13.png)

soll:
![image](https://user-images.githubusercontent.com/3855487/46024675-9a175980-c0e7-11e8-97f0-e3cd7d87f4c5.png)

Mit Trennung / Favoriten

ist:
![image](https://user-images.githubusercontent.com/3855487/46024865-f0849800-c0e7-11e8-95e6-32a4ed1f7124.png)

soll (optional):
![image](https://user-images.githubusercontent.com/3855487/46024943-0db96680-c0e8-11e8-8b1f-6728cbed01e2.png)

In diesem Beispiel ergibt es weniger Sinn, aber bei einer Länder-Auswahl kann man bspw. die Gruppe der Kontinente vernachlässigen.

**Comment by tbaddade** [comment]
In deinem ersten Bspl. wird vermutlich eine `optgroup` mit leerem `label` erzeugt.

Bei deiner zweiten Anregung wüsste ich jetzt nicht, wie man das sinnvoll erfassen soll. Sollen die `optgroup`s
- gar nicht angezeigt werden (ja/nein), 
- erst wenn die einzelne optgroup >= 5 {n} option besitzt
- erst wenn alle Favoriten zusammen >= 10 {n} option sind?

**Comment by alexplusde** [comment]
> In deinem ersten Bspl. wird vermutlich eine optgroup mit leerem label erzeugt.

Genau. Da sollten die Optionen dann nicht gruppiert werden.

> Bei deiner zweiten Anregung wüsste ich jetzt nicht, wie man das sinnvoll erfassen soll...

Eine Option "Favoriten ohne Gruppe darstellen" und Entwickler entscheiden lassen?
