### ISSUE TITLE
Formbuilder Initial mit objparam befüllen

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#738]
Da auf Slack wieder Probleme gemeldet werden bezüglich vorausgefüllten Feldern durch YCom, wäre es sinnvoll, die objparam, die auch beim Formularcode-Generator aus gutem Grund mit generiert werden, beim Erstellen eines Formbuilder-Blocks dabei wären. Z.B. mit zufälligem Formularnamen

**Comment by dergel** [comment]
Irgendwie verstehe ich das nicht ...
Kannst du mir das nochmal beschreiben ?

**Comment by alexplusde** [comment]
Beim Anlegen eines neuen Formulars im YForm Formbuilder sollte initial bereits eine Formulardefinition vorausgefüllt werden, die wichtige Parameter setzt und die Verwendung zeigt.

z.B. vorausgefüllt

```
objparams|form_name|yform-formbuilder-[random-index]
objparams|form_ytemplate|bootstrap
objparams|real_field_names|true

text|name|Name|||{"required":"required"}|
validate|empty|name|Bitte geben Sie einen Namen an.|
text|email|E-Mail-Adresse|||{"required":"required","type":"email"}|
validate|email|email|Bitte geben Sie eine gültige Email-Adresse an.|
validate|empty|email|Bitte geben Sie eine gültige E-Mail-Adresse an.|

action|tpl2email|emailtemplate|emaillabel|email@domain.de
```

insb. ging es mir um `form_name` - wenn dieser sich nicht unterscheidet bei mehr als einem Formular auf einer Website, gab es Probleme.

Mit dem o.g. Beispiel würde man jedoch auch den Formbuilder ein Stück selbsterklärender machen.

**Comment by tbaddade** [comment]
> Beim Anlegen eines neuen Formulars im YForm Formbuilder sollte initial bereits eine Formulardefinition vorausgefüllt werden

das ist bereits der Fall. Man sieht diese nur nicht. Initial werden diese objparams gesetzt.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php#L18-L103

> bei mehr als einem Formular auf einer Website, gab es Probleme.

@dergel Vielleicht reicht hier einen random Index anzuhängen.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php#L41

**Comment by dergel** [comment]
Zufällig geht nicht. Mittlerweile gibts ja auch einen EP und man kann sich per factory Class reinhängen. D.h. man kann schon auch selbst beeinflussen. Aber vielleicht anders in dieser Form .. 

Default gibt es keinen Formularnamen. Und anhand der vorhandenen Felddefinitionen wird ein individueller Formularname gesetzt (ausser man setzt ihn selbst) .. Dann ist das pro Formular unterschiedlich, auch wenn man welchee auf der selben Seite hat

**Comment by alexplusde** [comment]
Ich meinte einfach, einen leeren Formbuilder mit Pipe-Definitionen vorzubelegen. Wer sie nicht braucht, kann sie entfernen auf eigene Gefahr.

**Comment by dergel** [comment]
ach so .. na das ist ja noch einfacher und löst das Problem auch

**Comment by dergel** [comment]
vielleicht so. wir erstellen einen Button im Formbuilder mit "Dummyinhalte setzen" .. oder so ähnlich und dann wird das Beispiel eingesetzt. @alexplusde Lust das zu bauen ?

**Comment by alexplusde** [comment]
> @alexplusde Lust das zu bauen ?

Es scheitert nicht an der Lust. Der Extrabutton erschließt sich mir allerdings auch nicht. Einen Default-Wert für die Textarea könnte ich jedoch bereitstellen.

**Comment by dergel** [comment]
ist bereits drin. hier ein beispiel:

```
objparams|form_name|table-rex_hours_termine
objparams|form_ytemplate|bootstrap
objparams|form_showformafterupdate|0
objparams|real_field_names|true

checkbox|status|Status|0|0|||▢,▣|
text|title|Termintitel||0|
be_manager_relation|users|Teilnehmer|rex_hours_users|termin_id|4|0|

action|tpl2email|emailtemplate|emaillabel|email@domain.de
```

**Comment by alxndr-w** [comment]
Ich meinte nicht beim table Manager den Formular-Code, sondern die Area im Formbilder beim erstellen eines slices vorzubelegen.
