### ISSUE TITLE
Feature tabs/akkordeon - Element analog zu Fieldset

### ISSUE THREAD

**Issue by skerbis** [yakamara/yform#756]
Es wäre sehr nützlich, könnte man Tabs wie ein Fieldset einpflegen. (ähnlich mform)

**Comment by alexplusde** [comment]
Müsste mit eigener Value bereits möglich sein. Schon Mal prototypisch versucht umzusetzen?

**Comment by tbaddade** [comment]
Das funktioniert bereits mit html/php Value … Nutze ich sehr oft, wenn der Datensatz sprachabhängige Felder besitzt.

**Comment by alexplusde** [comment]
@tbaddade allerdings musst du dann manuell die Tabs befüllen und du hast dann ein Problem in Kombination mit fieldsets, wenn diese noch offen sind und vor dem Tab aber zu sein sollten.

Gut wäre, wenn fieldsets z.B. auch Tabs sein können und das Legend dann die Beschriftung des Tabs wären.

**Comment by skerbis** [comment]
@alexplusde nein, ich habe es noch nicht probiert. Ich hatte nur gerade ein ewig langes Formular von einer anderen Agentur vor mir, dass etwas aufgeräumter sein könnte. Dabei kam mir die Idee mit den Tabs. Dass man es per PHP und HTML machen kann, ist klar aber auch umständlich.

**Comment by alxndr-w** [comment]
@skerbis genügt https://github.com/alexplusde/yform_field/blob/main/lib/yform/value/tabs.php ?
