### ISSUE TITLE
YOrm: getRelatedDataset() liefert null, wenn relation vom typ inline relation 

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/yform#867]
`<b>Notice</b>: Undefined index: (Name der Relation) in redaxo\src\addons\yform\plugins\manager\lib\yform\manager\dataset.php:310<b>` statt Rückgabe des Datasets.

**Comment by alexplusde** [comment]
ich glaube, hier lag ein Missverständnis vor: ich hätte nach getRelatedCollection() fragen müssen, da der Datentyp 1:n Relationen zulässt. Hier sollte es dennoch nicht zu einer Notice kommen, sondern entweder zu einer adäquaten Meldung, oder keiner Ausgabe.

**Comment by alxndr-w** [comment]
Ich denke, das passt so.
