### ISSUE TITLE
BUG: Die Tabelle wurde nicht gefunden /  bei Redakteuren.  

### ISSUE THREAD

**Issue by skerbis** [yakamara/yform#956]
yform | 3.4.1

YForm wird den Redakteuren als Menüpunkt angezeigt. Klickt man drauf, erhält man 

> Die Tabelle wurde nicht gefunden

<img width="1045" alt="Bildschirmfoto 2020-10-28 um 13 27 25" src="https://user-images.githubusercontent.com/791247/97436100-bcf94500-1921-11eb-8caa-81f592f7ee98.png">

**Comment by dergel** [comment]
Wenn keine Rechte zugewiesen worden sind, oder ?

**Comment by skerbis** [comment]
Korrekt

**Comment by skerbis** [comment]
für alle die mitlesen. Es lässt sich aktuell in der boot.php vom Project-AddOn lösen: 

```php
if (( rex::isBackend() ) && ( !rex::getUser()->isAdmin()) ) {
    rex_extension::register('PAGES_PREPARED', function (rex_extension_point $ep) {	
    $page = rex_be_controller::getPageObject('yform');
    $page->setHidden(true);
});
}
```

**Comment by skerbis** [comment]
@dergel welche Rechte? Es gibt kein YForm-Recht außer für E-Mail-Templates

**Comment by dergel** [comment]
Das ist bereits in der aktuellen Version behoben

**Comment by skerbis** [comment]
@dergel 3.5.0-beta1
<img width="588" alt="Bildschirmfoto 2021-06-15 um 10 48 02" src="https://user-images.githubusercontent.com/791247/122022751-31a4c500-cdc7-11eb-9526-3ef7874129f9.png">

**Comment by alxndr-w** [comment]
Rechte an der Tabelle selbst vergeben? (Nicht an der Rolle)

**Comment by skerbis** [comment]
Es wurden Rechte an 3 Tabellen über die Rolle vergeben. 

<img width="687" alt="Bildschirmfoto 2021-06-15 um 10 52 26" src="https://user-images.githubusercontent.com/791247/122023408-cd363580-cdc7-11eb-9ee6-410796861c99.png">

**Comment by alxndr-w** [comment]
Geh Mal direkt in die YForm-Tabelle und da auf Tabelle bearbeiten, wo man auch Massenlöschung etc einstellt.

**Comment by skerbis** [comment]
Das hat damit nichts zu tun. Die NutzerInnen sollten den Menüpunkt nicht sehen. Auch wenn ich dort Rechte direkt in der Tabelleneinstellung vergebe, ändert sich nichts.

**Comment by alxndr-w** [comment]
Ach so rum meinst du. Ja.

**Comment by dergel** [comment]
äh quatsch.. das ist bereits erledigt. ich schliesse wieder

**Comment by dpf-dd** [comment]
Es verfolgt mich... yForm-Menüanzeige bei Nicht-Admins => Tabelle nicht gefunden... 

Das passiert bei mir nach wie vor bei jedem Projekt... Workaround ist mir bekannt und den verwende ich jetzt auch, aber warum bin ich scheinbar der Einzige mit dem Problem?

Redaxo und yForm sind auf aktuellem Stand (0 Updates verfügbar laut Installer)...

Ich habe eine Benutzerrolle "Redakteur" erstellt und die im Bild befindlichen Rechte vergeben/markiert.
Dennoch zeigt es bei dem User den Menüpunkt an (was es nicht soll) und zusätzlich kommt dann die Meldung "Tabelle nicht gefunden". Also im Prinzip alles so, wie in diesem Issue hier schonmal beschrieben...
![yform](https://user-images.githubusercontent.com/10958385/218718195-d7b65b0d-dd4a-4be0-8eeb-998f7c7e074c.png)

**Comment by cukabeka** [comment]
Same here.

yform | 4.0.4
REX Version | 5.14.2

**Comment by dergel** [comment]
Ich kann es in der aktuellen 4.2 Version nicht nachvollziehen. Ich schließe das mal wieder.

**Comment by alxndr-w** [comment]
Ich habe das hier reproduzierbar, Projekt  SU....M

**Comment by alxndr-w** [comment]
![image](https://github.com/yakamara/yform/assets/3855487/22e70206-8aff-4cfa-8b0e-128033eae9fb)

**Comment by dergel** [comment]
https://github.com/FriendsOfREDAXO/yform_spam_protection/issues/71

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_spam_protection/pull/72
